[phases.setup]
nixPkgs = ['nodejs_20', 'nodePackages.pnpm']

[phases.install]
cmds = [
    'cd packages/shared && pnpm install',
    'cd packages/augments-ui && pnpm install'
]

[phases.build]
cmds = [
    'cd packages/shared && pnpm run build',
    'cd packages/augments-ui && pnpm run build'
]

[start]
cmd = 'cd packages/augments-ui && pnpm start'

# Force cache invalidation
[cache]
paths = ['packages/shared/node_modules', 'packages/augments-ui/node_modules', 'packages/augments-ui/.next']
