/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'augments-gray-light': {
          1: 'var(--color-augments-gray-light-1)',
          2: 'var(--color-augments-gray-light-2)',
          3: 'var(--color-augments-gray-light-3)',
          4: 'var(--color-augments-gray-light-4)',
          5: 'var(--color-augments-gray-light-5)',
          6: 'var(--color-augments-gray-light-6)',
          7: 'var(--color-augments-gray-light-7)',
          8: 'var(--color-augments-gray-light-8)',
          9: 'var(--color-augments-gray-light-9)',
          10: 'var(--color-augments-gray-light-10)',
          11: 'var(--color-augments-gray-light-11)',
          12: 'var(--color-augments-gray-light-12)',
          a1: 'var(--color-augments-gray-light-a1)',
          a2: 'var(--color-augments-gray-light-a2)',
          a3: 'var(--color-augments-gray-light-a3)',
          a4: 'var(--color-augments-gray-light-a4)',
          a5: 'var(--color-augments-gray-light-a5)',
          a6: 'var(--color-augments-gray-light-a6)',
          a7: 'var(--color-augments-gray-light-a7)',
          a8: 'var(--color-augments-gray-light-a8)',
          a9: 'var(--color-augments-gray-light-a9)',
          a10: 'var(--color-augments-gray-light-a10)',
          a11: 'var(--color-augments-gray-light-a11)',
          a12: 'var(--color-augments-gray-light-a12)',
        },
        'augments-gray-dark': {
          1: 'var(--color-augments-gray-dark-1)',
          2: 'var(--color-augments-gray-dark-2)',
          3: 'var(--color-augments-gray-dark-3)',
          4: 'var(--color-augments-gray-dark-4)',
          5: 'var(--color-augments-gray-dark-5)',
          6: 'var(--color-augments-gray-dark-6)',
          7: 'var(--color-augments-gray-dark-7)',
          8: 'var(--color-augments-gray-dark-8)',
          9: 'var(--color-augments-gray-dark-9)',
          10: 'var(--color-augments-gray-dark-10)',
          11: 'var(--color-augments-gray-dark-11)',
          12: 'var(--color-augments-gray-dark-12)',
          a1: 'var(--color-augments-gray-dark-a1)',
          a2: 'var(--color-augments-gray-dark-a2)',
          a3: 'var(--color-augments-gray-dark-a3)',
          a4: 'var(--color-augments-gray-dark-a4)',
          a5: 'var(--color-augments-gray-dark-a5)',
          a6: 'var(--color-augments-gray-dark-a6)',
          a7: 'var(--color-augments-gray-dark-a7)',
          a8: 'var(--color-augments-gray-dark-a8)',
          a9: 'var(--color-augments-gray-dark-a9)',
          a10: 'var(--color-augments-gray-dark-a10)',
          a11: 'var(--color-augments-gray-dark-a11)',
          a12: 'var(--color-augments-gray-dark-a12)',
        },
        'augments-red-light': {
          1: 'var(--color-augments-red-light-1)',
          2: 'var(--color-augments-red-light-2)',
          3: 'var(--color-augments-red-light-3)',
          4: 'var(--color-augments-red-light-4)',
          5: 'var(--color-augments-red-light-5)',
          6: 'var(--color-augments-red-light-6)',
          7: 'var(--color-augments-red-light-7)',
          8: 'var(--color-augments-red-light-8)',
          9: 'var(--color-augments-red-light-9)',
          10: 'var(--color-augments-red-light-10)',
          11: 'var(--color-augments-red-light-11)',
          12: 'var(--color-augments-red-light-12)',
        },
        'augments-red-dark': {
          1: 'var(--color-augments-red-dark-1)',
          2: 'var(--color-augments-red-dark-2)',
          3: 'var(--color-augments-red-dark-3)',
          4: 'var(--color-augments-red-dark-4)',
          5: 'var(--color-augments-red-dark-5)',
          6: 'var(--color-augments-red-dark-6)',
          7: 'var(--color-augments-red-dark-7)',
          8: 'var(--color-augments-red-dark-8)',
          9: 'var(--color-augments-red-dark-9)',
          10: 'var(--color-augments-red-dark-10)',
          11: 'var(--color-augments-red-dark-11)',
          12: 'var(--color-augments-red-dark-12)',
        },
        'augments-green': {
          1: 'var(--color-augments-green-1)',
          2: 'var(--color-augments-green-2)',
          3: 'var(--color-augments-green-3)',
          4: 'var(--color-augments-green-4)',
          5: 'var(--color-augments-green-5)',
          6: 'var(--color-augments-green-6)',
          7: 'var(--color-augments-green-7)',
          8: 'var(--color-augments-green-8)',
          9: 'var(--color-augments-green-9)',
          10: 'var(--color-augments-green-10)',
          11: 'var(--color-augments-green-11)',
          12: 'var(--color-augments-green-12)',
          a1: 'var(--color-augments-green-a1)',
          a2: 'var(--color-augments-green-a2)',
          a3: 'var(--color-augments-green-a3)',
          a4: 'var(--color-augments-green-a4)',
          a5: 'var(--color-augments-green-a5)',
          a6: 'var(--color-augments-green-a6)',
          a7: 'var(--color-augments-green-a7)',
          a8: 'var(--color-augments-green-a8)',
          a9: 'var(--color-augments-green-a9)',
          a10: 'var(--color-augments-green-a10)',
          a11: 'var(--color-augments-green-a11)',
          a12: 'var(--color-augments-green-a12)',
        },
      },
    },
  },
  plugins: [],
}
