-- CreateEnum
CREATE TYPE "LLMModel" AS ENUM ('ANTHROPIC_CLAUDE_SONNET_4', 'ANTHROPIC_CLAUDE_OPUS_4');

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "model" "LLMModel" NOT NULL DEFAULT 'ANTHROPIC_CLAUDE_SONNET_4';
